version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    # colocar :Z no final se SELinux
    # give full permisson to write in mongo-data: chmod a+rwx
      - ./mongo-data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

  stay-auth:
    build: stay-auth/.
    ports:
      - "8080:8080"

  stay-hotel:
    build: stay-hotel/.
    ports:
      - "8081:8081"

  stay-booking:
    build: stay-booking/.
    ports:
      - "8083:8083"

volumes:
  mongo-data:
    driver: local
